name: Deploy Main to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/lams-frontend:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/lams-frontend:latest

      - name: Copy docker-compose.yml to VPS
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST_PROD }}
          username: ${{ secrets.VPS_USER_PROD }}
          key: ${{ secrets.VPS_SSH_KEY_PROD }}
          source: "./docker-compose.yml"
          target: "/opt/lams/lams-front"
          overwrite: true

      - name: Log in to Docker Hub on VPS and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST_PROD }}
          username: ${{ secrets.VPS_USER_PROD }}
          key: ${{ secrets.VPS_SSH_KEY_PROD }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            cd /opt/lams/lams-front

            # Безопасная очистка контейнеров и образов
            # Удаляем контейнеры, исключая те, что содержат в имени "mongo", "db", "postgres", "mysql", "redis"
            docker container ls -a --format "{{.Names}}" | grep -v -E 'mongo|db|postgres|mysql|redis' | xargs -r docker rm -f
            # Удаляем неиспользуемые образы
            docker image prune -a -f

            docker-compose pull
            docker-compose up -d
